//! Runtime descriptors for domain models.
//!
//! Descriptors provide runtime metadata about the structure of planning
//! solutions, entities, and variables. They are typically generated by
//! the derive macros.

mod entity;
mod problem_fact;
mod solution;
mod var_descriptor;

pub use entity::EntityDescriptor;
pub use problem_fact::ProblemFactDescriptor;
pub use solution::SolutionDescriptor;
pub use var_descriptor::VariableDescriptor;

#[cfg(test)]
mod tests;
